# Docker Compose para Churn API, MLflow, Prometheus e Grafana
services:

  churn-api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: churn-api 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    container_name: mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlruns:/mlruns
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always